# Generated by Django 6.0.4 on 2026-04-15 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='playedgame',
            old_name='score',
            new_name='duration_minutes',
        ),
        migrations.RemoveField(
            model_name='playedgame',
            name='rating',
        ),
        migrations.AddField(
            model_name='playedgame',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='ownedgame',
            unique_together={('user', 'game')},
        ),
        migrations.CreateModel(
            name='PlayerResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.IntegerField()),
                ('score', models.IntegerField(blank=True, null=True)),
                ('played_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='users.playedgame')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['place'],
            },
        ),
    ]
