"""
Django settings for blog project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
# В самом начале файла
import os
from dotenv import load_dotenv

# Загружаем переменные из .env
load_dotenv()

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0*8(j=de31!m!(#vpz+b3o*hkw&6guer^ilc2*2e4))4_bgg&w'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'entries.apps.EntriesConfig',
    'django.contrib.sites',  # ← ДОБАВИТЬ (обязательно для allauth)

    # allauth приложения
    'allauth',  # ← ДОБАВИТЬ
    'allauth.account',  # ← ДОБАВИТЬ
    'allauth.socialaccount',  # ← ДОБАВИТЬ (опционально, для соцсетей)
    'games',           # ← добавить
    'users',           # ← добавить
    'recommendations', # ← добавить
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',  # ← ДОБАВИТЬ ЭТУ СТРОКУ
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'blog.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'blog.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

LOGIN_URL = 'account_login'  # ← вместо 'login'
LOGIN_REDIRECT_URL = 'games'
ACCOUNT_LOGOUT_REDIRECT_URL = 'account_login'

# =====================================================
# НАСТРОЙКИ DJANGO-ALLAUTH (НОВАЯ ВЕРСИЯ)
# =====================================================

SITE_ID = 1

# Бэкенды аутентификации
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Настройки входа (новый формат)
ACCOUNT_LOGIN_METHODS = {'username', 'email'}  # вместо ACCOUNT_AUTHENTICATION_METHOD

# Настройки регистрации (новый формат)
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']  # вместо ACCOUNT_EMAIL_REQUIRED и ACCOUNT_USERNAME_REQUIRED

# Остальные настройки
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USERNAME_MIN_LENGTH = 3
ACCOUNT_PRESERVE_USERNAME_CASING = False
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 3

# Для разработки (письма в консоль)
#EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
#EMAIL_USE_LOCALTIME = True

# Перенаправления
LOGIN_REDIRECT_URL = 'games'
LOGOUT_REDIRECT_URL = 'account_login'
LOGIN_URL = 'account_login'

# =====================================================
# НАСТРОЙКИ EMAIL (GMAIL)
# =====================================================

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False

EMAIL_HOST_USER = 'boardguru10@gmail.com'           # ваш Gmail
EMAIL_HOST_PASSWORD = os.environ.get('GMAIL_PASSWORD')  # берём пароль из .env
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# 1. Указываем адрес, где будет жить сайт
# Вместо 'your_username' впишите свой реальный логин от PythonAnywhere
ALLOWED_HOSTS = ['your_username.pythonanywhere.com', '127.0.0.1']

# 2. Указываем папку, куда Django сложит все статические файлы (CSS, картинки)
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# 3. Обязательно выключаем режим отладки
DEBUG = False