"""
Django settings for blog project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Загружаем переменные из .env
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# =====================================================
# БЕЗОПАСНОСТЬ (SECURITY)
# =====================================================

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0*8(j=de31!m!(#vpz+b3o*hkw&6guer^ilc2*2e4))4_bgg&w'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = [
    'kravart10.pythonanywhere.com',
    '127.0.0.1',
    'localhost',
]

# =====================================================
# ПРИЛОЖЕНИЯ (INSTALLED APPS)
# =====================================================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # Обязательно для allauth

    # allauth приложения
    'allauth',
    'allauth.account',
    'allauth.socialaccount',

    # Ваши приложения
    'entries.apps.EntriesConfig',
    'games',
    'users',
    'recommendations',
]

# =====================================================
# МИДЛВАРЫ (MIDDLEWARE)
# =====================================================

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'users.middleware.SessionTrackingMiddleware',   # ← добавить эту строку
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'blog.urls'

# =====================================================
# ШАБЛОНЫ (TEMPLATES)
# =====================================================

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'blog.wsgi.application'

# =====================================================
# БАЗА ДАННЫХ (DATABASE)
# =====================================================

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# =====================================================
# ВАЛИДАЦИЯ ПАРОЛЕЙ
# =====================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# =====================================================
# ИНТЕРНАЦИОНАЛИЗАЦИЯ
# =====================================================

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True

# =====================================================
# СТАТИЧЕСКИЕ ФАЙЛЫ (STATIC FILES)
# =====================================================

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'static'

# =====================================================
# АУТЕНТИФИКАЦИЯ И ПЕРЕНАПРАВЛЕНИЯ
# =====================================================

LOGIN_URL = 'account_login'
LOGIN_REDIRECT_URL = 'games'

# =====================================================
# НАСТРОЙКИ DJANGO-ALLAUTH
# =====================================================

SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Настройки входа и регистрации
ACCOUNT_LOGIN_METHODS = {'username', 'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']

# Остальные настройки allauth
ACCOUNT_EMAIL_VERIFICATION = 'none'
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USERNAME_MIN_LENGTH = 3
ACCOUNT_PRESERVE_USERNAME_CASING = False
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 3
ACCOUNT_LOGOUT_REDIRECT_URL = 'account_login'
ACCOUNT_DEFAULT_HTTP_PROTOCOL = 'https'

# =====================================================
# НАСТРОЙКИ EMAIL (ПОЧТОВЫЙ СЕРВЕР PYTHONANYWHERE)
# =====================================================

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.pythonanywhere.com'
EMAIL_PORT = 25
EMAIL_USE_TLS = False
EMAIL_USE_SSL = False
EMAIL_HOST_USER = 'KravArt10'  # ваш логин PythonAnywhere (KravArt10)
EMAIL_HOST_PASSWORD = 'bac10_01cab'  # пароль от PythonAnywhere
DEFAULT_FROM_EMAIL = 'KravArt10@pythonanywhere.com'

# =====================================================
# НАСТРОЙКИ БЕЗОПАСНОСТИ ДЛЯ PYTHONANYWHERE
# =====================================================

# Доверенные источники для CSRF (обязательно для HTTPS)
CSRF_TRUSTED_ORIGINS = [
    'https://kravart10.pythonanywhere.com',
    'http://kravart10.pythonanywhere.com',
]

# Настройки безопасности сессий и cookies
SESSION_COOKIE_SECURE = True      # Передавать cookies только по HTTPS
SESSION_COOKIE_HTTPONLY = True    # Защита от XSS
CSRF_COOKIE_SECURE = True         # CSRF токен только по HTTPS

# Настройка для работы за reverse-proxy (PythonAnywhere)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')