# Generated by Django 6.0.4 on 2026-04-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('min_players', models.IntegerField(verbose_name='Мин. игроков')),
                ('max_players', models.IntegerField(verbose_name='Макс. игроков')),
                ('min_duration', models.IntegerField(blank=True, null=True, verbose_name='Мин. время (мин)')),
                ('max_duration', models.IntegerField(blank=True, null=True, verbose_name='Макс. время (мин)')),
                ('min_age', models.IntegerField(blank=True, null=True, verbose_name='Мин. возраст')),
                ('max_age', models.IntegerField(blank=True, null=True, verbose_name='Макс. возраст')),
                ('thematics', models.TextField(blank=True, verbose_name='Тематики')),
                ('categories', models.TextField(blank=True, verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
            },
        ),
    ]
